### ISSUE TITLE
Error in vignette SamplingStrata

### ISSUE THREAD

**Issue by arnaudfi** [barcaroli/SamplingStrata#4]
I think there is a problem in the SamplingStrata vignette, the line

`allocation <- bethel(strata1,cv[,1]) `

leads to the following error message 

> Error in bethel(strata1, cv[, 1]) : 
  Bethel: ncol(S)-5 must be equal to nrow(S)! See the online help: help('bth').

In fact, tables strata1 and cv are very different than S and T in bth. Is it the problem ? Or do your bethel function should work with strata1 and cv[,1] ?

Thanks

**Comment by arnaudfi** [comment]
It works in my configuration with 

`SamplingStrata::bethel(strata1,cv[1,])`

**Comment by barcaroli** [comment]
The error message "Bethel: ncol(S)-5 must be equal to nrow(S)! See the online help: help('bth')" is not of the "bethel" function in SamplingStrata package, but of the function "bth" in the bethel package. I can't understand how the two packages mixed up in this way...

**Comment by arnaudfi** [comment]
It is a local problem on my computer : if I do "

rm(list=ls())

"
Then there is no problem : the code on the vignette lead to the expected
result (without the "SamplingStrata::" in front of "bethel")

I guess this happen because I have a homemade R function called "bethel"
hidden in an old program and this function is more or less the same than
"bth"... So the problem is very typical of my installation,I wish I would
be able to delete the issue I have open but I dont find how to do that (I
am beginner with Git... Sorry)...

Thanks

Arnaud

Le ven. 4 févr. 2022 à 09:38, Giulio Barcaroli ***@***.***> a
écrit :

**Comment by barcaroli** [comment]
No problem, no need to delete the issue
